# Generated by Django 2.2.7 on 2019-12-02 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 2, 0, 40, 47, 642661, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
